### ISSUE TITLE
Default role typo

### ISSUE THREAD

**Issue by johncuthbertuk** [dwp/terraform-aws-kong-gateway#27]
https://github.com/dwp/terraform-aws-kong-gateway/blob/7577af677147e62c498b16802ed84ad62e961c2f/main.tf#L5

Typo, should be `embedded`

**Comment by alv-lop** [comment]
Closing issue as fixed in Release [0.0.28](https://github.com/dwp/terraform-aws-kong-gateway/releases/tag/0.0.28)
